config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "categories#index"

  Rails.application.routes.draw do
    resources :categories, except: %i[edit update] do
      resources :bookmarks, only: %i[new create show]
    end
    resources :bookmarks, only: [ :destroy ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category
  validates :category_id, uniqueness: { scope: :recipe_id }
  validates :comment, length: { minimum: 6 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks
  validates :name, uniqueness: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks
  has_many :categories, through: :bookmarks
  validates :description, presence: true
  validates :name, uniqueness: true
  validates :rating, numericality: { greater_than_or_equal_to: 0.0, less_than_or_equal_to: 10.0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
   @category = Category.find(params[:category_id])
   @bookmark = Bookmark.new
  end
  def create
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.category = @category
    if @bookmark.save
      redirect_to category_path(@category)
    else
      render :new, status: :unprocessable_entity
    end
end

def destroy
  @bookmark = Bookmark.find(params[:id])
  @bookmark.destroy
  redirect_to category_path(@bookmark.category), status: :see_other
end

private

def bookmark_params
  params.require(:bookmark).permit(:recipe_id, :comment)
end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories =Category.all
  end
  def show
    @category = Category.find(params[:id])
  end
  def new
    @category = Category.new
  end
  def create
    @category = Category.new(category_params)
    @category.save
    # No need for app/views/restaurants/create.html.erb
    redirect_to category_path(@category)
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, status: :see_other
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/bookmarks/new.html.erb
<h1>Which recipe would you like to add to your <%= @category.name %>list?</h1>
<%= simple_form_for [@category, @bookmark] do |f|%>
<%= f.association :recipe%>
<%= f.input :comment %>
<%= f.submit "add recipe"%>
<% end %>

app/views/categories/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path "banner.jpg" %>);">
  <div class="container">
    <h1>Cookbook</h1>
    <p>Save your favourites recipes</p>
  </div>
</div>

  <div class="container">
   <div class="d-flex justify-content-between py-3 align-items-center">
    <h1>List of Categories</h1>
    <%= link_to "new category", new_category_path, class: "btn btn-primary"%>
    </div>

  <div class="card-container">
   <% @categories.each do |category| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
      <h3><%=  link_to category.name.capitalize, category_path(category) %></h3>
      <p><%= category.recipes.length%></p>
      <%= link_to "X", category_path(category),data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "card-category-icon" %>
    </div>
   <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/categories/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path "recipe_banner.jpg" %>);">
  <div class="container">
    <h1><%= @category.name %></h2>
  </div>
</div>

<div class="container">
 <div class="d-flex justify-content-between py-3 align-items-center">
    <h1>Recipes</h2>
    <%= link_to "Add a recipe" ,new_category_bookmark_path(@category) ,class: "btn btn-primary"%>
  </div>
 <div class= "card-container">
  <% @category.bookmarks.each do |bookmark| %>
    <div class="card-recipe">
        <%= image_tag bookmark.recipe.image_url%>
          <div class="p-3">
              <h2><%= bookmark.recipe.name %></h2>
              <p><%= bookmark.recipe.description %></p>
          </div>
          <div class="card-recipe-infos">
             <h2><%= bookmark.comment %></h2>
             <p><%= bookmark.recipe.rating %></p>
             <%= link_to "X", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "card-category-icon" %>
          </div>
    </div>
 <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Cookbook" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
   <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
   <%= link_to root_path, class: "navbar-brand" do %>
   <%= image_tag "logo.jpg" %>
   <% end%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Messages</a>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>